version: "3"
services:
  app:
    container_name: docker-todo-api
    # if fails restart app
    restart: always
    # check for a docker file in the root directory
    build: .
    ports:
      - '3003:3003'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'